// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

/// @title SyntheticQwen
/// @notice GENERATED by tools/qwen3_convert.py — packed engine-v2 model config.
///         Do not edit by hand; regenerate instead.
library SyntheticQwen {
    function packedConfig() internal pure returns (bytes32[3] memory words) {
        words[0] = bytes32(uint256(0x30006002040200100000010000400101000000000000000000000000000000));
        words[1] = bytes32(uint256(0x10c6f7a10000000040000000000000000000faa90000000000000000));
        words[2] = bytes32(uint256(0x50d00000000000000000000000000000000000000000000000000000000));
    }
}
