// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {BLSSignatureChecker} from "@eigenlayer-middleware/BLSSignatureChecker.sol";
import {ISlashingRegistryCoordinator} from "@eigenlayer-middleware/interfaces/ISlashingRegistryCoordinator.sol";

import {GasKillerChatUnchecked} from "../src/examples/onchain-llm/GasKillerChatUnchecked.sol";
import {Qwen3_0_6B} from "../src/examples/onchain-llm/Qwen3_0_6B.sol";
import {Qwen3Engine} from "../src/examples/onchain-llm/Qwen3Engine.sol";
import {Qwen3SegEngine} from "../src/examples/onchain-llm/Qwen3SegEngine.sol";

/// @title DeployOnchainLLMDirectoryScript
/// @notice Wires a consumer to the REAL Qwen3-0.6B weights already living on Sepolia as
///         24,364 CREATE data contracts behind the two-level directory root
///         `0x9d1dDc25c098DA26417D0A061b647f3a3511D7b0` (20 pages + 1 root; every one of
///         the 24,385 codehashes verified == keccak(0x00 || payload)). No weights are
///         uploaded here — this script only deploys code.
/// @dev Deploys `Qwen3Engine` + `Qwen3SegEngine` (both stateless; reuse via ENGINE /
///      SEG_ENGINE env to skip) and `GasKillerChatUnchecked` in DIRECTORY mode:
///      `weightsRoot = QWEN3_ROOT`, `weightsManifest = 0`.
///
///      The plain `GasKillerChat` CANNOT be used here: its constructor calls
///      `engine.checkArtifacts`, measured at 104.3M gas over this artifact set, which
///      exceeds Sepolia's ~60M block gas limit. `GasKillerChatUnchecked` skips exactly
///      that call and nothing else — run the validation after deploy instead:
///
///        # byte identity (the real check; no gas cap involved)
///        python3 src/examples/onchain-llm/tools/verify_onchain_directory.py \
///            --artifacts .context/qwen3/artifacts --ledger .context/qwen3/deploy-ledger \
///            --rpc $RPC
///
///        # semantic shape check, needs a node with --rpc.gascap >= 200000000
///        python3 src/examples/onchain-llm/tools/verify_onchain_directory.py \
///            --artifacts .context/qwen3/artifacts --ledger .context/qwen3/deploy-ledger \
///            --rpc $BIG_GASCAP_RPC --engine $ENGINE \
///            --config-from .context/qwen3/artifacts/vectors.json
///
///      Required env:
///        AVS_ADDRESS                    AVS service manager
///                                       (tenop: 0xac91Ef6C23Bc683E5f8dd6c210033BE3f95Dc62e)
///        SIG_CHECKER_ADDRESS            existing BLSSignatureChecker, or set
///        REGISTRY_COORDINATOR_ADDRESS   to deploy a fresh one against it
///                                       (tenop: 0x574369B88ae0E4db774b822Fe921090b0ab8c06b)
///      Optional env:
///        QWEN3_ROOT   directory root (defaults to the deployed 0.6B root below)
///        ENGINE       reuse an already-deployed Qwen3Engine instead of deploying one
///        SEG_ENGINE   reuse an already-deployed Qwen3SegEngine instead of deploying one
///                     (tenop already has one at 0x6785256C51301464415f367afa39411271dEF8b1)
contract DeployOnchainLLMDirectoryScript is Script {
    /// @notice The live Sepolia Qwen3-0.6B two-level directory root (401-byte payload:
    ///         1 STOP prelude byte + 20 page addresses)
    address internal constant QWEN3_0_6B_ROOT = 0x9d1dDc25c098DA26417D0A061b647f3a3511D7b0;

    GasKillerChatUnchecked public chat;

    function run() public {
        address avsAddress = vm.envOr("AVS_ADDRESS", address(0));
        address sigChecker = vm.envOr("SIG_CHECKER_ADDRESS", address(0));
        address registryCoordinator = vm.envOr("REGISTRY_COORDINATOR_ADDRESS", address(0));
        address weightsRoot = vm.envOr("QWEN3_ROOT", QWEN3_0_6B_ROOT);
        address existingEngine = vm.envOr("ENGINE", address(0));
        address existingSegEngine = vm.envOr("SEG_ENGINE", address(0));
        require(avsAddress != address(0), "AVS_ADDRESS must be set");
        require(weightsRoot != address(0), "QWEN3_ROOT must be nonzero (directory mode)");
        require(weightsRoot.code.length > 0, "QWEN3_ROOT has no code on this chain");

        // Generated by tools/qwen3_convert.py from the real 0.6B checkpoint; identical to
        // .context/qwen3/artifacts/vectors.json's packedConfig.
        bytes32[3] memory packedConfig = Qwen3_0_6B.packedConfig();

        vm.startBroadcast();

        if (sigChecker == address(0)) {
            require(registryCoordinator != address(0), "Set SIG_CHECKER_ADDRESS or REGISTRY_COORDINATOR_ADDRESS");
            sigChecker = address(new BLSSignatureChecker(ISlashingRegistryCoordinator(registryCoordinator)));
            console.log("Deployed BLSSignatureChecker at:", sigChecker);
        }

        Qwen3Engine engine = existingEngine == address(0) ? new Qwen3Engine() : Qwen3Engine(existingEngine);
        Qwen3SegEngine segEngine =
            existingSegEngine == address(0) ? new Qwen3SegEngine() : Qwen3SegEngine(existingSegEngine);

        // Directory mode: weightsRoot = the live root, weightsManifest = 0. The
        // constructor's artifact check is the ONLY thing skipped vs GasKillerChat.
        chat = new GasKillerChatUnchecked(avsAddress, sigChecker, engine, weightsRoot, bytes32(0), packedConfig);

        vm.stopBroadcast();

        // Grep-friendly wiring facts for the operator harness / shard coordinator.
        console.log("DEPLOYED_TARGET=%s", address(chat));
        console.log("ENGINE=%s", address(engine));
        console.log("SEG_ENGINE=%s", address(segEngine));
        console.log("WEIGHTS_ROOT=%s", weightsRoot);
        console.log("MANIFEST=0x0000000000000000000000000000000000000000000000000000000000000000");
        console.log("SIG_CHECKER=%s", sigChecker);
        console.log("AVS_ADDRESS=%s", avsAddress);
        console.log(string.concat("PACKED_CFG_0=", vm.toString(packedConfig[0])));
        console.log(string.concat("PACKED_CFG_1=", vm.toString(packedConfig[1])));
        console.log(string.concat("PACKED_CFG_2=", vm.toString(packedConfig[2])));
    }
}
