// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {IBLSSignatureCheckerTypes} from "@eigenlayer-middleware/interfaces/IBLSSignatureChecker.sol";

import {StateUpdateType} from "../../src/StateChangeHandlerLib.sol";
import {DataContractLib} from "../../src/examples/onchain-llm/DataContractLib.sol";
import {GasKillerLLM} from "../../src/examples/onchain-llm/GasKillerLLM.sol";
import {Llama2} from "../../src/examples/onchain-llm/Llama2.sol";
import {LlamaEngine} from "../../src/examples/onchain-llm/LlamaEngine.sol";
import {LlamaMath} from "../../src/examples/onchain-llm/LlamaMath.sol";
import {LlamaTokenizer} from "../../src/examples/onchain-llm/LlamaTokenizer.sol";
import {Stories260K} from "../../src/examples/onchain-llm/Stories260K.sol";

/// @notice Mock BLS checker: reports 100% of quorum stake as signed, so every
///         verifyAndUpdate passes the 66% threshold. The test acts as the operator set.
contract MockBLSSignatureChecker {
    function checkSignatures(
        bytes32,
        bytes calldata quorumNumbers,
        uint32,
        IBLSSignatureCheckerTypes.NonSignerStakesAndSignature memory
    ) external pure returns (IBLSSignatureCheckerTypes.QuorumStakeTotals memory totals, bytes32) {
        totals.signedStakeForQuorum = new uint96[](quorumNumbers.length);
        totals.totalStakeForQuorum = new uint96[](quorumNumbers.length);
        for (uint256 i = 0; i < quorumNumbers.length; i++) {
            totals.signedStakeForQuorum[i] = uint96(1e18);
            totals.totalStakeForQuorum[i] = uint96(1e18);
        }
        return (totals, bytes32(0));
    }
}

/// @notice Tests the on-chain LLM against bit-exact vectors generated by the Python
///         reference (tools/reference.py), which itself reproduces llama2.c run.c
///         byte-for-byte on the stories260K checkpoint at temperature 0.
contract OnchainLLMTest is Test {
    using stdJson for string;
    using LlamaTokenizer for LlamaTokenizer.Tok;

    /// @dev keccak256("gasKiller.stateTracker") - 1 (StateTracker slot, gate-exempt)
    bytes32 internal constant TRACKER_SLOT = 0xdebfdfd5a50ad117c10898d68b5ccf0893c6b40d4f443f902e2e7646601bdeaf;

    address internal avsAddress = address(0x1234);

    GasKillerLLM internal llm;
    LlamaEngine internal engine;
    MockBLSSignatureChecker internal blsChecker;

    bytes internal weightsBlob;
    bytes internal tokBlob;
    string internal vectors;

    string internal prompt;
    uint16[] internal promptIds;

    event StoryTold(
        uint256 indexed transitionIndex, bytes32 indexed newRoot, string prompt, string story, uint16[] tokens
    );

    function setUp() public {
        string memory root = vm.projectRoot();
        weightsBlob = vm.parseBytes(
            string.concat("0x", vm.readFile(string.concat(root, "/test/fixtures/onchain-llm/weights.hex")))
        );
        tokBlob = vm.parseBytes(
            string.concat("0x", vm.readFile(string.concat(root, "/test/fixtures/onchain-llm/tokenizer.hex")))
        );
        vectors = vm.readFile(string.concat(root, "/test/fixtures/onchain-llm/vectors.json"));

        prompt = vectors.readString(".prompt");
        promptIds = _toUint16(vectors.readUintArray(".promptIds"));

        // deploy model artifacts exactly as the deploy script would
        address tokPtr = DataContractLib.write(tokBlob);
        uint256 nChunks = (weightsBlob.length + DataContractLib.MAX_PAYLOAD - 1) / DataContractLib.MAX_PAYLOAD;
        bytes memory dir = abi.encodePacked(tokPtr);
        for (uint256 i = 0; i < nChunks; ++i) {
            uint256 start = i * DataContractLib.MAX_PAYLOAD;
            uint256 len = weightsBlob.length - start;
            if (len > DataContractLib.MAX_PAYLOAD) len = DataContractLib.MAX_PAYLOAD;
            dir = abi.encodePacked(dir, DataContractLib.write(_slice(weightsBlob, start, len)));
        }
        address dirPtr = DataContractLib.write(dir);

        blsChecker = new MockBLSSignatureChecker();
        engine = new LlamaEngine();
        llm = new GasKillerLLM(avsAddress, address(blsChecker), engine, dirPtr, Stories260K.packedConfig());
    }

    // ---------------------------------------------------------------- math

    function test_ExpQ32MatchesReference() public view {
        int256[] memory pairs = abi.decode(vm.parseBytes(vectors.readString(".expVectors")), (int256[]));
        for (uint256 i = 0; i < pairs.length; i += 2) {
            assertEq(int256(LlamaMath.expQ32(pairs[i])), pairs[i + 1], "expQ32 mismatch");
        }
    }

    function test_ExpQ32RevertsOnPositiveInput() public {
        vm.expectRevert(LlamaMath.ExpArgPositive.selector);
        this.expQ32External(1);
    }

    /// @dev external wrapper so expectRevert applies to a call, not an internal jump
    function expQ32External(int256 x) external pure returns (uint256) {
        return LlamaMath.expQ32(x);
    }

    function test_IsqrtMatchesReference() public view {
        int256[] memory pairs = abi.decode(vm.parseBytes(vectors.readString(".isqrtVectors")), (int256[]));
        for (uint256 i = 0; i < pairs.length; i += 2) {
            assertEq(int256(LlamaMath.isqrt(uint256(pairs[i]))), pairs[i + 1], "isqrt mismatch");
        }
    }

    function testFuzz_IsqrtIsFloorSqrt(uint256 x) public pure {
        uint256 r = LlamaMath.isqrt(x);
        // floor sqrt of any uint256 fits in 128 bits, so r*r cannot overflow
        assertLe(r * r, x, "r*r > x");
        // (r+1)^2 > x; when r+1 == 2^128 that holds trivially for every uint256
        if (r < type(uint128).max) {
            assertGt((r + 1) * (r + 1), x, "(r+1)^2 <= x");
        }
    }

    // ----------------------------------------------------------- tokenizer

    function test_TokenizerEncodeMatchesReference() public view {
        LlamaTokenizer.Tok memory tok = LlamaTokenizer.load(tokBlob);
        for (uint256 i = 0; i < 5; ++i) {
            string memory base = string.concat(".encodeVectors[", vm.toString(i), "]");
            string memory text = vectors.readString(string.concat(base, ".text"));
            uint256[] memory expected = vectors.readUintArray(string.concat(base, ".ids"));
            uint16[] memory got = tok.encode(bytes(text));
            assertEq(got.length, expected.length, "encode length mismatch");
            for (uint256 j = 0; j < got.length; ++j) {
                assertEq(uint256(got[j]), expected[j], "encode id mismatch");
            }
        }
    }

    function test_TokenizerDecodeMatchesReference() public view {
        LlamaTokenizer.Tok memory tok = LlamaTokenizer.load(tokBlob);
        uint16[] memory ids = _toUint16(vectors.readUintArray(".genShort"));
        bytes memory got = tok.decode(ids, ids.length, promptIds[promptIds.length - 1]);
        assertEq(string(got), vectors.readString(".storyShort"), "decode mismatch");
    }

    // ------------------------------------------------------------- forward

    function test_ForwardLogitsMatchReference() public view {
        Llama2.Config memory cfg = Llama2.unpack(Stories260K.packedConfig());
        Llama2.Layout memory o = Llama2.layout(cfg);
        Llama2.Buffers memory b = Llama2.newBuffers(cfg, 1);
        Llama2.forward(cfg, o, weightsBlob, b, promptIds[0], 0);

        int256[] memory expected = abi.decode(vm.parseBytes(vectors.readString(".logitsPos0")), (int256[]));
        assertEq(b.logits.length, expected.length, "logit count mismatch");
        for (uint256 i = 0; i < expected.length; ++i) {
            assertEq(b.logits[i], expected[i], "logit mismatch");
        }
    }

    function test_DryRunMatchesReferenceStory() public view {
        (string memory story, uint16[] memory tokens) = llm.dryRun(prompt, 32);
        uint256[] memory expected = vectors.readUintArray(".genShort");
        assertEq(tokens.length, expected.length, "token count mismatch");
        for (uint256 i = 0; i < tokens.length; ++i) {
            assertEq(uint256(tokens[i]), expected[i], "token mismatch");
        }
        assertEq(story, vectors.readString(".storyShort"), "story mismatch");
    }

    /// @notice Full-length generation against the reference; heavy, so opt-in:
    ///         ONCHAIN_LLM_LONG_TEST=true forge test --match-test LongStory
    function test_LongStoryMatchesReference() public view {
        if (!vm.envOr("ONCHAIN_LLM_LONG_TEST", false)) return;
        (string memory story, uint16[] memory tokens) = llm.dryRun(prompt, 200);
        uint256[] memory expected = vectors.readUintArray(".genLong");
        assertEq(tokens.length, expected.length, "token count mismatch");
        for (uint256 i = 0; i < tokens.length; ++i) {
            assertEq(uint256(tokens[i]), expected[i], "token mismatch");
        }
        assertEq(story, vectors.readString(".storyLong"), "story mismatch");
    }

    // ------------------------------------------------- Gas Killer consumer

    function test_TellStoryWritesExactlyOneAppSlot() public {
        (string memory story, uint16[] memory tokens) = llm.dryRun(prompt, 8);
        bytes32 expectedRoot = llm.computeStoryRoot(llm.storyRoot(), prompt, story);

        vm.record();
        vm.expectEmit(true, true, true, true, address(llm));
        emit StoryTold(1, expectedRoot, prompt, story, tokens);
        llm.tellStory(prompt, 8);

        (, bytes32[] memory writes) = vm.accesses(address(llm));
        assertGt(writes.length, 0, "no writes recorded");
        for (uint256 i = 0; i < writes.length; ++i) {
            assertTrue(writes[i] == llm.STORY_ROOT_SLOT() || writes[i] == TRACKER_SLOT, "unexpected storage write");
        }
        assertEq(llm.storyRoot(), expectedRoot, "story root not updated");
        assertEq(llm.stateTransitionCount(), 1, "transition not tracked");
    }

    function test_TellStoryChainsCommitments() public {
        llm.tellStory(prompt, 4);
        bytes32 rootAfterFirst = llm.storyRoot();

        (string memory story2,) = llm.dryRun("The dragon", 4);
        llm.tellStory("The dragon", 4);
        assertEq(llm.storyRoot(), llm.computeStoryRoot(rootAfterFirst, "The dragon", story2), "commitment chain broken");
    }

    /// @notice End-to-end Gas Killer flow: the test plays the operator set — simulate
    ///         tellStory off-chain (dryRun), sign the single-STORE + LOG3 diff via the
    ///         mock quorum, and apply it with verifyAndUpdate. The transformer never
    ///         runs in the applying transaction.
    function test_VerifyAndUpdateAppliesStoryDiff() public {
        vm.roll(100);

        // --- operator side: simulate the tracked function, extract the state diff ---
        (string memory story, uint16[] memory tokens) = llm.dryRun(prompt, 8);
        uint256 transitionIndex = llm.stateTransitionCount();
        bytes32 newRoot = llm.computeStoryRoot(llm.storyRoot(), prompt, story);

        StateUpdateType[] memory types = new StateUpdateType[](2);
        bytes[] memory args = new bytes[](2);
        types[0] = StateUpdateType.STORE;
        args[0] = abi.encode(llm.STORY_ROOT_SLOT(), newRoot);
        types[1] = StateUpdateType.LOG3;
        args[1] = abi.encode(
            abi.encode(prompt, story, tokens),
            keccak256("StoryTold(uint256,bytes32,string,string,uint16[])"),
            bytes32(transitionIndex + 1),
            newRoot
        );
        bytes memory storageUpdates = abi.encode(types, args);

        bytes32 msgHash =
            sha256(abi.encode(transitionIndex, address(llm), GasKillerLLM.tellStory.selector, storageUpdates));

        // --- chain side: quorum-verified diff application, no inference executed ---
        IBLSSignatureCheckerTypes.NonSignerStakesAndSignature memory sig;
        vm.expectEmit(true, true, true, true, address(llm));
        emit StoryTold(transitionIndex + 1, newRoot, prompt, story, tokens);
        llm.verifyAndUpdate(
            msgHash,
            hex"00",
            uint32(block.number - 1),
            storageUpdates,
            transitionIndex,
            GasKillerLLM.tellStory.selector,
            sig
        );

        assertEq(llm.storyRoot(), newRoot, "diff not applied");
        assertEq(llm.stateTransitionCount(), transitionIndex + 1, "transition not tracked");
    }

    function test_ConstructorRejectsMismatchedConfig() public {
        bytes32[3] memory cfg = Stories260K.packedConfig();
        // corrupt the weight blob length field (bits 160..191 of word 2)
        cfg[2] = bytes32(uint256(cfg[2]) ^ (uint256(1) << 170));
        address dir = llm.weightsDirectory();
        vm.expectRevert();
        new GasKillerLLM(avsAddress, address(blsChecker), engine, dir, cfg);
    }

    // ------------------------------------------------------------- helpers

    function _toUint16(uint256[] memory xs) internal pure returns (uint16[] memory out) {
        out = new uint16[](xs.length);
        for (uint256 i = 0; i < xs.length; ++i) {
            out[i] = uint16(xs[i]);
        }
    }

    function _slice(bytes memory data, uint256 start, uint256 len) internal pure returns (bytes memory out) {
        out = new bytes(len);
        assembly ("memory-safe") {
            let src := add(add(data, 0x20), start)
            let dst := add(out, 0x20)
            for { let i := 0 } lt(i, len) { i := add(i, 0x20) } {
                mstore(add(dst, i), mload(add(src, i)))
            }
        }
    }
}
