// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

// src/examples/onchain-llm/Stories260K.sol

/// @title Stories260K
/// @notice GENERATED by tools/convert.py — packed model configuration for the
///         Stories260K checkpoint. Do not edit by hand; regenerate instead.
library Stories260K {
    function packedConfig() internal pure returns (bytes32[3] memory words) {
        words[0] = bytes32(uint256(0x4000ac05080402000200080020010000000000000000000000000000000000));
        words[1] = bytes32(uint256(0xe0d0e0e100f0e0f0f0f0c0e0000000000000000000000000000000000000000));
        words[2] = bytes32(uint256(0x5a82799a00082f800000165200000000000000000000000000000000));
    }
}
